require '\Dev\workspace\RPP\bean\common.rb'
require '/Dev/workspace/RPP/bean/common.rb'
require 'D:\Dev\workspace\RPP\bean\common.rb'
require 'D:/Dev/workspace/RPP/bean/common.rb'
require '.\..\..\bean\common.rb'
require './../../bean/common.rb'
require '../../bean/common.rb'
require '..\..\bean/common.rb'