drop table RefSex;
drop table RefBreed;
drop table RefCoat;
drop table RefBlinder;
drop table RefShoes;

drop table Weather;
drop table Job;
drop table Meeting;
drop table Race;
drop table Forecast;
drop table Weight;
drop table Origin;
drop table Jockey;
drop table Trainer;
drop table Owner;
drop table Breeder;
drop table Horse;
drop table Runner;
